### PR TITLE
fix(style): decorate titles and nav properly

### PR DESCRIPTION
**Pull request by niklaas**
These design decisions are based on the original styles of Even for
hugo.

### CODE REVIEW

**Comment by Keats** [comment]
So if I remember correctly some of the changes I've made to themes I ported was to not use custom fonts. Since the fonts are not loaded in the HTML, I don't think those changes have much effect do they?

**Comment by niklaas** [comment]
They do have great have effect because, e.g. in the case of the decorating font, the browser will ultimately fall back to `serif`. In addition, I improved the size of the font and titles of posts are no longer colored in `$main-colour`.

From my point of view, these changes make the design much more coherent. And it does serve the original design much better. (I use these changes on my personal blog notebook.niklaas.eu if you would like to compare them to the current state.)

In addition, if you'd like to, I am happy to submit another PR that deals with bundling the preferred fonts automatically.

**Comment by Keats** [comment]
I agree for the serif/sans-serif but eg in `font-family: Chancery, cursive, LiSu, sans-serif;` it's unlikely that the user will have Chancery and LiSu installed so it's effectively `font-family: cursive, sans-serif;`. Not a huge deal though.

**Comment by niklaas** [comment]
You're right. I added them to be in line with what the original Even specifies only. Shall we bundle these fonts in this implementation of Even? I could add the necessary changes in this PR (instead of creating a separate PR).

**Comment by Keats** [comment]
Yep, keep it as lean as possible. I would prefer not having any webfont by default and we could mention in the README how to load them if someone wants to.

**Comment by niklaas** [comment]
OK. Since I plan to include the supplementary fonts for my blog, I'll add instructions for the README in another PR as soon as I can. So this can be left as is? This way, users of this theme can decide on their own if they want to bundle the fonts. I they do, their blog visitors will see the fonts, otherwise their visitors' browsers will fall-back to the default fonts.

**Pull request merged**
